Updating init script and defaults.

diff --git a/debian/tmda-smtp.tmda-ofmipd.init b/debian/tmda-smtp.tmda-ofmipd.init
--- a/debian/tmda-smtp.tmda-ofmipd.init
+++ b/debian/tmda-smtp.tmda-ofmipd.init
@@ -23,25 +23,26 @@
 # Suite 330, Boston, MA 02111-1307 USA
 #
 ### BEGIN INIT INFO
-# Provides:          tmda-server
+# Provides:          tmda-ofmipd
 # Required-Start:    $network $local_fs
-# Required-Stop:
+# Required-Stop:     $network $local_fs
 # Should-Start:      $named
-# Should-Stop:
+# Should-Stop:       $named
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: <Enter a short description of the sortware>
-# Description:       <Enter a long description of the software>
-#                    <...>
-#                    <...>
+# Short-Description: Proxy server for sending mail tagged by TMDA.
+# Description:       This server acts as a SMTP proxy server, adding
+#                    TMDA processing to outgoing mail to support things
+#                    like tagged addresses and auto-whitelisting of
+#                    addresses you send mail to.
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
 DAEMON=/usr/bin/tmda-ofmipd # Introduce the server's location here
-NAME=#PACKAGE              # Introduce the short server's name here
-DESC=#PACKAGE              # Introduce a short description here
-LOGDIR=/var/log/tmda  # Log directory to use
+NAME=tmda-ofmipd            # Introduce the short server's name here
+DESC="TMDA proxy server"    # Introduce a short description here
+LOGDIR=/var/log             # Log directory to use
 
 PIDFILE=/var/run/$NAME.pid
 
@@ -63,17 +64,18 @@ DIETIME=10              # Time to wait for the server to die, in seconds
                         # started (on start or restart) the script will
                         # stall to try to determine if it is running
                         # If it is not set and the server takes time
-                        # to setup a pid file the log message might 
+                        # to setup a pid file the log message might
                         # be a false positive (says it did not start
                         # when it actually did)
-                        
+
 LOGFILE=$LOGDIR/$NAME.log  # Server logfile
-#DAEMONUSER=tmda   # Users to run the daemons as. If this value
-                        # is set start-stop-daemon will chuid the server
+DAEMONUSER=tofmipd      # User to run the daemons as. Daemon runs as
+                        # root and changes to this user shortly after
+                        # starting.
 
 # Include defaults if available
 if [ -f /etc/default/$NAME ] ; then
-	. /etc/default/$NAME
+    . /etc/default/$NAME
 fi
 
 # Use this if you want the user to explicitly set 'RUN' in
@@ -119,39 +121,32 @@ running() {
     # No pidfile, probably no daemon present
     [ ! -f "$PIDFILE" ] && return 1
     pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
+    running_pid $pid python || return 1
     return 0
 }
 
 start_server() {
-# Start the process using the wrapper
-        if [ -z "$DAEMONUSER" ] ; then
-            start_daemon -p $PIDFILE $DAEMON -- $DAEMON_OPTS
-            errcode=$?
-        else
-# if we are using a daemonuser then change the user id
-            start-stop-daemon --start --quiet --pidfile $PIDFILE \
-                        --chuid $DAEMONUSER \
-                        --exec $DAEMON -- $DAEMON_OPTS
-            errcode=$?
-        fi
-	return $errcode
+    # The daemon is a python process, so locating, killing, etc. by process
+    # name is no good, and we need a pidfile. tmda-ofmipd doesn't do its
+    # own pidfile, so start-stop-daemon has to handle it (the --make-pidfile
+    # option). This also requires that the daemon not fork itself, since that
+    # would change the pid and invalidate the pidfile, thus the -f option
+    # to the daemon and the --background option to start-stop-daemon.
+    # Furthermore, the deamon has to do its own user id changing, because
+    # it may need to be root to read the private key file, and will drop
+    # root privilages afterward.
+    start-stop-daemon --start --quiet --oknodo --make-pidfile --background \
+                      --exec $DAEMON --pidfile $PIDFILE \
+                      -- -f -u $DAEMONUSER $DAEMON_OPTS
+    errcode=$?
+    return $errcode
 }
 
 stop_server() {
 # Stop the process using the wrapper
-        if [ -z "$DAEMONUSER" ] ; then
-            killproc -p $PIDFILE $DAEMON
-            errcode=$?
-        else
-# if we are using a daemonuser then look for process that match
-            start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-                        --user $DAEMONUSER \
-                        --exec $DAEMON
-            errcode=$?
-        fi
-
-	return $errcode
+    killproc -p $PIDFILE $DAEMON
+    errcode=$?
+    return $errcode
 }
 
 reload_server() {
@@ -164,27 +159,27 @@ reload_server() {
 
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+    # Is it really dead?
+        sleep "$DIETIME"s
+        if running ; then
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
+        fi
+    fi
+    rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC " "$NAME"
+        log_daemon_msg "Starting $DESC " "$NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
@@ -195,7 +190,7 @@ case "$1" in
             # NOTE: Some servers might die some time after they start,
             # this code will detect this issue if STARTTIME is set
             # to a reasonable value
-            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time 
+            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
             if  running ;  then
                 # It's ok, the server started and is running
                 log_end_msg 0
@@ -207,12 +202,12 @@ case "$1" in
             # Either we could not start it
             log_end_msg 1
         fi
-	;;
+        ;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-			errcode=0
+            errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -228,14 +223,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-			errcode=0
+            errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
-	;;
+        ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-		errcode=0
+        errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -243,7 +238,7 @@ case "$1" in
         [ -n "$STARTTIME" ] && sleep $STARTTIME
         running || errcode=$?
         log_end_msg $errcode
-	;;
+        ;;
   status)
 
         log_daemon_msg "Checking status of $DESC" "$NAME"
@@ -284,13 +279,13 @@ case "$1" in
           #    log_end_msg 1
           #    exit 1
           # fi
-                                                                                    #;;
+          #;;
 
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+        N=/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
 
 exit 0
